site_name: MacintoshPortable.info
site_url: https://macintoshportable.info
repo_url: https://github.com/rezafouladian/macintoshportable
nav:
  - Home: index.md
  - Troubleshooting:
    - Sad Mac Errors: SadMac.md
    - Startup Sequence: StartupSequence.md
    - Testing: Testing.md
    - Display: 
      - Display Testing: DisplayTesting.md
  - Docs: 
    - Components: Components.md
    - Memory Map: MemoryMap.md
    - Signal Descriptions: SignalDescriptions.md
    - Hardware & Accessories: HardwareAndAccessories.md
    - More Resources: MoreResources.md
    - Test Manager: TestManager.md
    - 9MB of RAM on the M5126: M5126-9MB.md
    - Slim Cards: SlimCards.md
    - Unsorted: Unsorted.md
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto

    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - search.suggest
markdown_extensions:
  - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
plugins:
  - glightbox
  - search
