site_name: MacintoshPortable.info
site_url: https://macintoshportable.info
repo_url: https://github.com/rezafouladian/macintoshportable
nav:
  - Home: index.md
  - Troubleshooting:
    - Testing: Testing.md
    - Display: 
      - Display Testing: DisplayTesting.md
  - Docs: 
    - Components: Components.md
    - Memory Map: MemoryMap.md
    - Signal Descriptions: SignalDescriptions.md
    - Hardware & Accessories: HardwareAndAccessories.md
    - More Resources: MoreResources.md
  - GitHub: https://github.com/rezafouladian/macintoshportable
  - Startup: StartupSequence.md
markdown_extensions:
  - footnotes